export const GET_EVENTLIST_REQUEST = 'GET_TRACKS_REQUEST';
export const GET_EVENTLIST_SUCCESS = 'GET_TRACKS_SUCCESS';
export const GET_EVENTLIST_FAILURE = 'GET_TRACKS_FAILURE';

export const POST_EVENT_REQUEST = 'POST_EVENT_REQUEST';
export const POST_EVENT_SUCCESS = 'POST_EVENT_SUCCESS';
export const POST_EVENT_FAILURE = 'POST_EVENT_FAILURE';

export const PUT_EVENT_REQUEST = 'PUT_EVENT_REQUEST';
export const PUT_EVENT_SUCCESS = 'PUT_EVENT_SUCCESS';
export const PUT_EVENT_FAILURE = 'PUT_EVENT_FAILURE';

export const REMOVE_EVENT_REQUEST = 'REMOVE_EVENT_REQUEST';
export const REMOVE_EVENT_SUCCESS = 'REMOVE_EVENT_SUCCESS';
export const REMOVE_EVENT_FAILURE = 'REMOVE_EVENT_FAILURE';
